const QuestionData = [
  {
    Q: "1",
    type: "math",
    instruction:
      "Mathematics is the most loved and also the most feared subjects by students across the world. Have you been worrying about your upcoming math test? Practice these 30 maths quiz questions to ensure you are at the top of your game",
    question: "Combine terms: 12a + 26b -4b - 16a.",
    option: ["4a + 22b", "-28a + 30b", "-4a + 22b", " 28a + 30b"],
    answer: "-4a + 22b",
    nextquestion: "2",
    userStatus: "not_visited",
  },
  {
    Q: "2",
    type: "physics",
    instruction:
      "Physics Questions: Solved 254 Physics Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: " What happens to your weight when you are in a lift which goes down?",
    option: ["Decreases", "Increases", "Decreases and then increases", "None of these"],
    answer: "Decreases",
    nextquestion: "3",
    prevquestion: "1",
    userStatus: "not_visited",
  },
  {
    Q: "3",
    type: "chemistry",
    instruction:
      "Chemistry Questions: Solved 165 Chemistry Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: "Which of the following is the most used semiconductor?",
    option: ["Silicon", "Lead", "Aluminum", "Nickel"],
    answer: "Silicon",
    nextquestion: "4",
    prevquestion: "2",
    userStatus: "not_visited",
  },
  {
    Q: "4",
    type: "math",
    instruction:
      "Mathematics is the most loved and also the most feared subjects by students across the world. Have you been worrying about your upcoming math test? Practice these 30 maths quiz questions to ensure you are at the top of your game",
    question: "Simplify: (4 - 5) - (13 - 18 + 2).",
    option: ["-1", "-2", "1", "2"],
    answer: "2",
    nextquestion: "5",
    prevquestion: "3",
    userStatus: "not_visited",
  },
  {
    Q: "5",
    type: "physics",
    instruction:
      "Physics Questions: Solved 254 Physics Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: "The slope of a velocity-time graph represents?",
    option: ["Distance", "Acceleration", "Momentum", "Mass"],
    answer: "Acceleration",
    nextquestion: "6",
    prevquestion: "4",
    userStatus: "not_visited",
  },
  {
    Q: "6",
    type: "physics",
    instruction:
      "Physics Questions: Solved 254 Physics Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: " Higgs boson is also known as",
    option: ["Man particle", "God particle", "Lucy particle", "None of the above"],
    answer: "Man particle",
    nextquestion: "7",
    prevquestion: "5",
    userStatus: "not_visited",
  },
  {
    Q: "7",
    type: "math",
    instruction:
      "Mathematics is the most loved and also the most feared subjects by students across the world. Have you been worrying about your upcoming math test? Practice these 30 maths quiz questions to ensure you are at the top of your game",
    question: "What is |-26|?",
    option: ["-26", "26", "0", "1"],
    answer: "26",
    nextquestion: "8",
    prevquestion: "6",
    userStatus: "not_visited",
  },
  {
    Q: "8",
    type: "chemistry",
    instruction:
      "Chemistry Questions: Solved 165 Chemistry Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: " Which of the following is the lowest layer of the atmosphere?",
    option: ["Stratosphere", "Troposphere", "Mesosphere", "Exosphere"],
    answer: "Troposphere",
    nextquestion: "9",
    prevquestion: "7",
    userStatus: "not_visited",
  },
  {
    Q: "9",
    type: "math",
    instruction:
      "Mathematics is the most loved and also the most feared subjects by students across the world. Have you been worrying about your upcoming math test? Practice these 30 maths quiz questions to ensure you are at the top of your game",
    question: "Solve for x: 2x - y = (3/4)x + 6.",
    option: ["(y + 6)/5", "4(y + 6)/5", "(y + 6)", "4(y - 6)/5"],
    answer: "4(y + 6)/5",
    nextquestion: "10",
    prevquestion: "8",
    userStatus: "not_visited",
  },
  {
    Q: "10",
    type: "chemistry",
    instruction:
      "Chemistry Questions: Solved 165 Chemistry Questions and answers section with explanation for various online exam preparation, various interviews, General Knowledge Category online test. Category Questions section with detailed description, explanation will help you to master the topic.",
    question: " Which of the following is a polymer of chloroethene?",
    option: ["Polyvinyl chloride (PVC)", "Nylon", "Polystyrene", "Terylene"],
    answer: "Polyvinyl chloride (PVC)",
    prevquestion: "9",
    userStatus: "not_visited",
  },
];
export default QuestionData;
